apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- svc.yaml
images:
- name: nginx
  newName: 323974325951.dkr.ecr.ap-northeast-2.amazonaws.com/nginx
  newTag: v1.0.1
